kind: Deployment
apiVersion: apps/v1
metadata:
  name: kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kafka
  template:
    metadata:
      labels:
        name: kafka
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: 192.168.120.62:30181
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 10.105.52.103:2181,10.96.92.201:2181,10.98.116.40:2181
        - name: KAFKA_CREATE_TOPICS
          value: mytopic:2:1
